camel:
  server-port: 5003
  springboot:
    main-run-controller: true
  dataformat:
    json-jackson:
      auto-discover-object-mapper: true
server:
  port: 8083

zeebe:
  client:
    max-execution-threads: 100
    number-of-workers: 5
    evenly-allocated-max-jobs: "#{${zeebe.client.max-execution-threads} / ${zeebe.client.number-of-workers}}"
  broker:
    contactpoint: "localhost:26500"

ams:
  local:
    enabled: false
  timeout: 60000

pesacore:
  base-url: https://qaoperations01.oneacrefund.org
  auth-header: 51f56774-8ef6-11ec-b909-0242ac120002
  endpoint:
    verification: /api/paymentHub/Verification
    confirmation: /api/paymentHub/Confirmation

management:
  endpoint:
    health:
      probes:
        enabled: true
      liveness:
        enabled: true
      readiness:
        enabled: true
logging:
  level:
    ROOT: INFO
